window.blag = [
  { date: '2013-03-06',
    title: 'OMG HTML5 view super performant. I still can\'t belive it',
    text: 'talk: <a href="http://www.youtube.com/watch?v=f48_wJjmEw0">www.youtube.com/watch?v=f48_wJjmEw0</a> <br />slides: <a href="http://www.slideshare.net/befamous/html5-devconf-oct-2012-tech-talk">http://www.slideshare.net/befamous/html5-devconf-oct-2012-tech-talk</a> <p /> spread the word!' },
  { date: '2012-11-20',
    title: 'You don\'t understand section tag? You\'re right.',
    text: '<a href="http://www.netmagazine.com/features/truth-about-structuring-html5-page">http://www.netmagazine.com/features/truth-about-structuring-html5-page</a>' },
  { date: '2012-11-15',
    title: 'detecting CSS animation support',
    text: '<a href="https://developer.mozilla.org/en-US/docs/CSS/CSS_animations/Detecting_CSS_animation_support">https://developer.mozilla.org/en-US/docs/CSS/CSS_animations/Detecting_CSS_ani...</a>' },
  { date: '2012-11-12',
    title: 'What worried me in Backbone now has a tutorial :)',
    text: '<a href="https://paydirtapp.com/blog/backbone-in-practice-memory-management-and-event-bindings/">https://paydirtapp.com/blog/backbone-in-practice-memory-management-and-event-...</a>' },
  { date: '2012-11-12',
    title: 'What worried me in Backbone now has a tutorial :)',
    text: '<a href="https://paydirtapp.com/blog/backbone-in-practice-memory-management-and-event-bindings/">https://paydirtapp.com/blog/backbone-in-practice-memory-management-and-event-...</a>' },
  { date: '2012-11-09',
    title: 'Nice summary of not-often-needed html5 stuff',
    text: '<a href="http://davidwalsh.name/more-html5-apis">http://davidwalsh.name/more-html5-apis</a>' },
  { date: '2012-11-09',
    title: 'Nice summary of not-often-needed html5 stuff',
    text: '<a href="http://davidwalsh.name/more-html5-apis">http://davidwalsh.name/more-html5-apis</a>' },
  { date: '2012-10-25',
    title: 'feeling secure? don\'t',
    text: '<a href="https://crypto.stanford.edu/~dabo/pubs/abstracts/ssl-client-bugs.html">https://crypto.stanford.edu/~dabo/pubs/abstracts/ssl-client-bugs.html</a>' },
  { date: '2012-10-14',
    title: 'create new syntax for your JS',
    text: '<a href="https://github.com/mozilla/sweet.js">https://github.com/mozilla/sweet.js</a>' },
  { date: '2012-10-01',
    title: 'DOMNodeInserted imlementation without mutation events',
    text: '<a href="http://www.backalleycoder.com/2012/04/25/i-want-a-damnodeinserted/">http://www.backalleycoder.com/2012/04/25/i-want-a-damnodeinserted/</a>' },
  { date: '2012-09-30',
    title: 'more in-depth performance details in V8',
    text: '<a href="http://mrale.ph/blog/2012/09/23/grokking-v8-closures-for-fun.html">http://mrale.ph/blog/2012/09/23/grokking-v8-closures-for-fun.html</a>' },
  { date: '2012-09-21',
    title: 'Namespaces are old-school',
    text: '<a href="http://blog.millermedeiros.com/namespaces-are-old-school/">http://blog.millermedeiros.com/namespaces-are-old-school/</a>' },
  { date: '2012-07-27',
    title: 'JS to JS binary streaming',
    text: '<div><a href="http://binaryjs.com/">http://binaryjs.com/</a><br /></div><div>let&#39;s make a radio station!</div>' },
  { date: '2012-07-23',
    title: 'comfortable tool for hand-crafting sprites',
    text: '<a href="http://www.spritecow.com">http://www.spritecow.com</a>' },
  { date: '2012-07-06',
    title: 'fun with particle animation in DOM',
    text: '<a href="http://fontbomb.ilex.ca/">http://fontbomb.ilex.ca/</a><p />When I tried similar stuff 5 years ago I got up to 2 frames per eternity. Browsers got fast...' },
  { date: '2012-07-02',
    title: 'Anonymous publishing',
    text: 'Read the replies too: <a href="http://cryptome.org/2012/06/anon-pub-dead.htm">http://cryptome.org/2012/06/anon-pub-dead.htm</a>' },
  { date: '2012-06-29',
    title: 'It\'s too much! :)',
    text: '<a href="http://www.htmlfivecan.com">http://www.htmlfivecan.com</a>' },
  { date: '2012-06-21',
    title: 'comfortable regex testing',
    text: '<div><a href="http://refiddle.com/">http://refiddle.com/</a><br /></div><div>lovely</div>' },
  { date: '2012-06-06',
    title: 'Finally! depth added to touchscreen buttons',
    text: '<a href="http://www.tactustechnology.com/">http://www.tactustechnology.com/</a>' },
  { date: '2012-06-01',
    title: 'Some useful tables for javascript operators',
    text: '<a href="http://zero.milosz.ca/">http://zero.milosz.ca/</a>' },
  { date: '2012-05-18',
    title: 'js.js - not that silly when you consider security purposes',
    text: '<a href="https://github.com/jterrace/js.js">https://github.com/jterrace/js.js</a>' },
  { date: '2012-05-17',
    title: 'Shadows in JS',
    text: '<a href="https://github.com/gre/illuminated.js">https://github.com/gre/illuminated.js</a>' },
  { date: '2012-05-17',
    title: 'Particle animation on canvas',
    text: '<a href="http://www.mrspeaker.net/dev/parcycle/">http://www.mrspeaker.net/dev/parcycle/</a>' },
  { date: '2012-05-17',
    title: 'And other shadows in JS',
    text: '<a href="http://indamix.github.com/real-shadow/">http://indamix.github.com/real-shadow/</a>' },
  { date: '2012-04-19',
    title: 'free visual goodies',
    text: '<a href="http://creativemarket.com/free-goods">http://creativemarket.com/free-goods</a>' },
  { date: '2012-02-28',
    title: 'Bare metal web optimization',
    text: '<a href="http://chemeo.com/doc/technology/slow-start">http://chemeo.com/doc/technology/slow-start</a>' },
  { date: '2011-12-16',
    title: 'That\'s something to celebrate!',
    text: '<a href="http://www.geek.com/articles/geek-pick/microsoft-decides-to-automatically-update-internet-explorer-for-everyone-20111215/">http://www.geek.com/articles/geek-pick/microsoft-decides-to-automatically-update-internet-explorer-for-everyone-20111215/</a>' },
  { date: '2011-11-21',
    title: 'fullscreen from javascript',
    text: '<a href="http://jlongster.com/2011/11/21/canvas.html">http://jlongster.com/2011/11/21/canvas.html</a>' },
  { date: '2011-11-14',
    title: 'CSS3 hover inspiration',
    text: '<a href="http://tympanus.net/Tutorials/OriginalHoverEffects/index.html">http://tympanus.net/Tutorials/OriginalHoverEffects/index.html</a>' },
  { date: '2011-11-07',
    title: 'Before you claim it...',
    text: '<a href="http://www.w2lessons.com/2011/04/you-dont-know-javascript.html">http://www.w2lessons.com/2011/04/you-dont-know-javascript.html</a>' },
  { date: '2011-10-10',
    title: 'CSS3 transitions tool',
    text: '<a href="http://matthewlein.com/ceaser/">http://matthewlein.com/ceaser/</a>' },
  { date: '2011-10-10',
    title: '[resources] textures for webdesign',
    text: '<a href="http://subtlepatterns.com/">http://subtlepatterns.com/</a>' },
  { date: '2011-10-07',
    title: 'Javascript performance lecture from Yahoo',
    text: '<a href="http://yuilibrary.com/theater/nicholas-zakas-stoyan-stefanov-ross-harmes-julien-lecomte-matt-sweeney/zakas-hpjs/">http://yuilibrary.com/theater/nicholas-zakas-stoyan-stefanov-ross-harmes-juli...</a>' },
  { date: '2011-10-07',
    title: 'Advertising media queries',
    text: '<a href="http://mediaqueri.es/">http://mediaqueri.es/</a> <br />My humble opinion: everything I saw there on the main page was <br />possible with CSS2, nevertheless media queries are great.' },
  { date: '2011-09-27',
    title: '[pl] Przygotowanie do prowadzenia zajęć, czyli o html5 po polsku',
    text: 'wprowadzenie: <a href="http://webhosting.pl/HTML.5.i.CSS.3.czyli.jak.bedziemy.tworzyc.strony.WWW.w.przyszlosci">http://webhosting.pl/HTML.5.i.CSS.3.czyli.jak.bedziemy.tworzyc.strony.WWW.w.p...</a> <br />krótko o wszystkim: <a href="http://html5.glitchmr.pl/">http://html5.glitchmr.pl/</a> <p /> kurs html: <a href="http://pl.html.net/">http://pl.html.net/</a> <p /> już nie po polsku: <br />książka: <a href="http://diveintohtml5.org/">http://diveintohtml5.org/</a> <br />tutorial: <a href="http://www.html-5-tutorial.com/index.htm">http://www.html-5-tutorial.com/index.htm</a>' },
  { date: '2011-09-21',
    title: 'javascript renderer - tree.js',
    text: '<a href="https://github.com/mrdoob/three.js/">https://github.com/mrdoob/three.js/</a> [OMG]' },
  { date: '2011-09-19',
    title: 'CSS for selection',
    text: '<span class="css-punctuation">:</span><span class="css-punctuation">:</span><span class="css-selector">-moz-selection </span><span class="css-punctuation">{ </span><span class="css-identifier">background</span><span class="css-punctuation">: </span><span class="css-colorcode">#5af</span><span class="css-punctuation">; </span><span class="css-identifier">color</span><span class="css-punctuation">: </span><span class="css-colorcode">#fff</span><span class="css-punctuation">; </span><span class="css-identifier">text-shadow</span><span class="css-punctuation">: </span><span class="css-value">none</span><span class="css-punctuation">; </span><span class="css-punctuation">}</span><br /> <span class="css-punctuation">:</span><span class="css-punctuation">:</span><span class="css-selector">selection </span><span class="css-punctuation">{ </span><span class="css-identifier">background</span><span class="css-punctuation">: </span><span class="css-colorcode">#5af</span><span class="css-punctuation">; </span><span class="css-identifier">color</span><span class="css-punctuation">: </span><span class="css-colorcode">#fff</span><span class="css-punctuation">; </span><span class="css-identifier">text-shadow</span><span class="css-punctuation">: </span><span class="css-value">none</span><span class="css-punctuation">; </span><span class="css-punctuation">}</span>' },
  { date: '2011-09-12',
    title: 'Infinite sets in JS',
    text: '<a href="http://streamjs.org/">http://streamjs.org/</a> //if you did prolog, nothing surprises you' },
  { date: '2011-09-08',
    title: 'Backend for mobile apps',
    text: '<a href="https://www.parse.com/">https://www.parse.com/</a>' },
  { date: '2011-09-06',
    title: 'First elegant tool for cross-browser testing I found',
    text: '<a href="http://www.browserstack.com">http://www.browserstack.com</a>' },
  { date: '2011-09-02',
    title: 'Nice introduction to visual design',
    text: '<a href="http://www.visualmess.com/">http://www.visualmess.com/</a>' },
  { date: '2011-08-29',
    title: 'Paper crypt',
    text: 'Left here to read later: <a href="https://www.grc.com/offthegrid.htm">https://www.grc.com/offthegrid.htm</a>' },
  { date: '2011-08-29',
    title: 'Sounds easy...',
    text: 'Learning vim <a href="http://yannesposito.com/Scratch/en/blog/Learn-Vim-Progressively/">http://yannesposito.com/Scratch/en/blog/Learn-Vim-Progressively/</a>' },
  { date: '2011-08-26',
    title: 'intro to html5 on mobile',
    text: '<a href="http://www.engineyard.com/blog/2011/mobile-development-with-html5/">http://www.engineyard.com/blog/2011/mobile-development-with-html5/</a>' },
  { date: '2011-08-26',
    title: 'This looks important ;)',
    text: '<a href="http://w3fools.com/">http://w3fools.com/</a>' },
  { date: '2011-08-25',
    title: 'Why Iceland should be in the news but is not',
    text: '<a href="http://sacsis.org.za/site/article/728.1">http://sacsis.org.za/site/article/728.1</a> <br />By Deena Stryker <p /> Mirror: <p /> An Italian radio program’s story about Iceland’s on-going revolution <br />is a stunning example of how little our media tells us about the rest <br />of the world. Americans may remember that at the start of the 2008 <br />financial crisis, Iceland literally went bankrupt. The reasons were <br />mentioned only in passing, and since then, this little-known member of <br />the European Union fell back into oblivion. <p /> As one European country after another fails or risks failing, <br />imperiling the Euro, with repercussions for the entire world, the last <br />thing the powers that be want is for Iceland to become an example. <br />Here`s why: <p /> Five years of a pure neo-liberal regime had made Iceland, (population <br />320 thousand, no army), one of the richest countries in the world. In <br />2003 all the country’s banks were privatized, and in an effort to <br />attract foreign investors, they offered on-line banking whose minimal <br />costs allowed them to offer relatively high rates of return. The <br />accounts, called IceSave, attracted many English and Dutch small <br />investors. But as investments grew, so did the banks’ foreign debt. <br />In 2003 Iceland’s debt was equal to 200 times its GNP, but in 2007, it <br />was 900 percent. The 2008 world financial crisis was the coup de <br />grace. The three main Icelandic banks, Landbanki, Kapthing and <br />Glitnir, went belly up and were nationalized, while the Kroner lost <br />85% of its value with respect to the Euro. At the end of the year <br />Iceland declared bankruptcy. <p /> Contrary to what could be expected, the crisis resulted in Icelanders <br />recovering their sovereign rights, through a process of direct <br />participatory democracy that eventually led to a new Constitution. <br />But only after much pain. <p /> Geir Haarde, the Prime Minister of a Social Democratic coalition <br />government, negotiated a two million one hundred thousand dollar loan, <br />to which the Nordic countries added another two and a half million. <br />But the foreign financial community pressured Iceland to impose <br />drastic measures. The FMI and the European Union wanted to take over <br />its debt, claiming this was the only way for the country to pay back <br />Holland and Great Britain, who had promised to reimburse their <br />citizens. <p /> Protests and riots continued, eventually forcing the government to <br />resign. Elections were brought forward to April 2009, resulting in a <br />left-wing coalition which condemned the neoliberal economic system, <br />but immediately gave in to its demands that Iceland pay off a total of <br />three and a half million Euros. This required each Icelandic citizen <br />to pay 100 Euros a month (or about $130) for fifteen years, at 5.5% <br />interest, to pay off a debt incurred by private parties vis a vis <br />other private parties. It was the straw that broke the reindeer’s <br />back. <p /> What happened next was extraordinary. The belief that citizens had to <br />pay for the mistakes of a financial monopoly, that an entire nation <br />must be taxed to pay off private debts was shattered, transforming the <br />relationship between citizens and their political institutions and <br />eventually driving Iceland’s leaders to the side of their <br />constituents. The Head of State, Olafur Ragnar Grimsson, refused to <br />ratify the law that would have made Iceland’s citizens responsible for <br />its bankers’ debts, and accepted calls for a referendum. <p /> Of course the international community only increased the pressure on <br />Iceland. Great Britain and Holland threatened dire reprisals that <br />would isolate the country. As Icelanders went to vote, foreign <br />bankers threatened to block any aid from the IMF. The British <br />government threatened to freeze Icelander savings and checking <br />accounts. As Grimsson said: “We were told that if we refused the <br />international community’s conditions, we would become the Cuba of the <br />North. But if we had accepted, we would have become the Haiti of the <br />North.” (How many times have I written that when Cubans see the dire <br />state of their neighbor, Haiti, they count themselves lucky.) <p /> In the March 2010 referendum, 93% voted against repayment of the debt. <br /> The IMF immediately froze its loan. But the revolution (though not <br />televised in the United States), would not be intimidated. With the <br />support of a furious citizenry, the government launched civil and <br />penal investigations into those responsible for the financial crisis. <br />Interpol put out an international arrest warrant for the ex-president <br />of Kaupthing, Sigurdur Einarsson, as the other bankers implicated in <br />the crash fled the country. <p /> But Icelanders didn`t stop there: they decided to draft a new <br />constitution that would free the country from the exaggerated power of <br />international finance and virtual money. (The one in use had been <br />written when Iceland gained its independence from Denmark, in 1918, <br />the only difference with the Danish constitution being that the word <br />‘president’ replaced the word ‘king’.) <p /> To write the new constitution, the people of Iceland elected <br />twenty-five citizens from among 522 adults not belonging to any <br />political party but recommended by at least thirty citizens. This <br />document was not the work of a handful of politicians, but was written <br />on the internet. The constituent’s meetings are streamed on-line, and <br />citizens can send their comments and suggestions, witnessing the <br />document as it takes shape. The constitution that eventually emerges <br />from this participatory democratic process will be submitted to <br />parliament for approval after the next elections. <p /> Some readers will remember that Iceland’s ninth century agrarian <br />collapse was featured in Jared Diamond’s book by the same name. Today, <br />that country is recovering from its financial collapse in ways just <br />the opposite of those generally considered unavoidable, as confirmed <br />yesterday by the new head of the IMF, Christine Lagarde to Fareed <br />Zakaria. The people of Greece have been told that the privatization of <br />their public sector is the only solution. And those of Italy, Spain <br />and Portugal are facing the same threat. <p /> They should look to Iceland. Refusing to bow to foreign interests, <br />that small country stated loud and clear that the people are <br />sovereign. <p /> That’s why it is not in the news anymore.' },
  { date: '2011-08-24',
    title: 'power tweaks for intel GMA linux',
    text: '<a href="http://www.phoronix.com/scan.php?page=article&item=intel_i915_power&num=1">http://www.phoronix.com/scan.php?page=article&item=intel_i915_power&num=1</a>' },
  { date: '2011-08-23',
    title: 'Collaborative editing tool',
    text: '<p>(has problems with encoding - not as cool as I thought) <a href="http://beta.etherpad.org/">http://beta.etherpad.org/</a></p>' },
  { date: '2011-08-22',
    title: 'html5 tools',
    text: '<a href="http://smashinghub.com/excellent-html5-coding-tools.htm">http://smashinghub.com/excellent-html5-coding-tools.htm</a> (canvas cheat-sheet!)' },
  { date: '2011-08-18',
    title: 'Canvas sketching - simple and well done',
    text: '<a href="http://sketchub.com/">http://sketchub.com/</a>' },
  { date: '2011-08-18',
    title: 'CSS can draw too',
    text: 'CSS GUI icons <a href="http://nicolasgallagher.com/pure-css-gui-icons/demo/">http://nicolasgallagher.com/pure-css-gui-icons/demo/</a>' },
  { date: '2011-08-18',
    title: 'canvas speedup',
    text: 'That`s what i`ve been waiting for <br /><a href="http://www.html5rocks.com/en/tutorials/canvas/performance/">http://www.html5rocks.com/en/tutorials/canvas/performance/</a>' },
  { date: '2011-08-17',
    title: 'Colorization algorithm',
    text: 'Awesome <a href="http://www.cs.huji.ac.il/~yweiss/Colorization/">http://www.cs.huji.ac.il/~yweiss/Colorization/</a>' },
  { date: '2011-08-17',
    title: 'jQuery performance tips',
    text: 'A nice article to show to the less experienced, but promising: <br /><a href="http://www.artzstudio.com/2009/04/jquery-performance-rules/">http://www.artzstudio.com/2009/04/jquery-performance-rules/</a>' },
  { date: '2011-08-10',
    title: 'CSS id selector speed',
    text: '<a href="http://oli.jp/2011/ids/">http://oli.jp/2011/ids/</a> <br /><a href="http://stevesouders.com/efws/css-selectors/csscreate.php">http://stevesouders.com/efws/css-selectors/csscreate.php</a>' },
  { date: '2011-08-10',
    title: 'nounproject - icons for everything',
    text: '<a href="http://thenounproject.com/">http://thenounproject.com/</a>' },
  { date: '2011-08-10',
    title: '-noMorePrefixingByHand-CSS3: !important;',
    text: '<a href="http://css3generator.com/">http://css3generator.com/</a>' },
  { date: '2011-08-10',
    title: 'HTML5 - less popular tricks',
    text: '<a href="http://html5-demos.appspot.com/static/html5-whats-new/template/index.html">http://html5-demos.appspot.com/static/html5-whats-new/template/index.html</a>' } ]
